---
- name: Install Vector | DEB install
  become: true
  ansible.builtin.apt:
    deb: https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb
    state: present
  notify: restart vector service