---
- name: Install Vector | YUM install
  become: true
  become_method: sudo
  become_user: root
  ansible.builtin.yum:
    name: https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.{{ ansible_architecture }}.rpm
    state: present
  notify: restart vector service