---
- name: Verify
  hosts: all
  tasks:
    - name: include variables
      include_vars: ../../playbook/roles/vector_role/defaults/main.yml
    
    - name: Vector check package RPM status 
      package:
        name: https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.{{ ansible_architecture }}.rpm
        state: "installed"
      check_mode: yes
      register: pkg_status_rpm
      when: ansible_os_family == "RedHat"

    - name: "Vector test package RPM is installed"
      assert:
        that:
          - not pkg_status_rpm.changed
      when: ansible_os_family == "RedHat"

    - name: Vector check package DEB status
      package:
        deb: https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb
        state: "present"
      check_mode: yes
      register: pkg_status_deb
      when: ansible_os_family == "Debian"

    - name: "Vector test package DEB is installed"
      assert:
        that:
          - not pkg_status_deb.changed
      when: ansible_os_family == "Debian"
    
    - name: Return service state information as fact data
      service_facts:

    - name: Vector test service is running
      ignore_errors: true
      assert:
        that:
          -  ansible_facts.services['vector.service']['state'] != 'running'

    - name: "Vector retrieve information from path '{{ vector_config_dir }}/vector.yml'"
      ignore_errors: true
      stat:
        path: "{{ vector_config_dir }}/vector.yml"
      register: remote_file
    
    - name: "tomcat - assert that '{{ vector_config_dir }}/vector.yml' file is created correctly"
      ignore_errors: true
      assert:
        that:
          - "remote_file.stat.exists"
          - "remote_file.stat.isreg"
          - "remote_file.stat.path == '{{ vector_config_dir }}/vector.yml'"
          - "remote_file.stat.mode == '0644'"